trigger:
- master

strategy:
  matrix:
    Ubuntu_16:
      imageName: ubuntu-16.04
      localRedis: false
      publishArtifact: true
    Ubuntu_18:
      imageName: ubuntu-18.04
      localRedis: true
      publishArtifact: false
    Windows:
      imageName: windows-latest
      localRedis: false
      publishArtifact: false
    OSX:
      imageName: macOS-latest
      localRedis: false
      publishArtifact: false

jobs:
- template: build_template.yml
  parameters:
    name: $(strategy)
    vmImage: $(localRedis)
    localRedis: $(localRedis)
    publishArtifact: $(publishArtifact)