variables:
  configuration: release
  platform: any cpu

trigger:
- master

jobs:
- template: build_template.yml
  parameters:
    name: Ubuntu 16.04
    vmImage: ubuntu-16.04
    localRedis: true
    publishArtifact: true

- template: build_template.yml
  parameters:
    name: Ubuntu 18.04
    vmImage: ubuntu-18.04
    localRedis: true

- template: build_template.yml
  parameters:
    name: Windows
    vmImage: windows-2019

- template: build_template.yml
  parameters:
    name: OSX
    vmImage: macOS-latest
