variables:
  configuration: release
  platform: any cpu

trigger:
- master

phases:
- template: build_template.yml
  parameters:
    name: Linux
    queue: Hosted Ubuntu 1604
    publish_artifact: true

- template: build_template.yml
  parameters:
    name: Windows
    queue: Hosted VS2017
    local_redis: false

- template: build_template.yml
  parameters:
    name: Mac
    queue: Hosted macOS Preview
    local_redis: false
