variables:
  configuration: release
  platform: any cpu

trigger:
- master

jobs:
- template: build_template.yml
  parameters:
    name: Linux
    vmImage: ubuntu-16.04
    localRedis: true
    publishArtifact: true

- template: build_template.yml
  parameters:
    name: Windows
    vmImage: windows-2019

- template: build_template.yml
  parameters:
    name: Mac
    vmImage: macOS-latest
