name: Build & Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-18.04
          - ubuntu-20.04
          - ubuntu-22.04
          - windows-latest
          - macOS-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.0.x
          7.0.x

    - if: ${{ runner.os == 'Linux' }}
      name: Install Redis
      run: bash ./RedisCore.Tests/install_redis_debian.sh

    - name: Build
      run: dotnet build

    - name: Test
      run: dotnet test --no-build --verbosity normal
      env:
        LOCAL_REDIS: ${{ runner.os == 'Linux' }}
        AZURE_REDIS_HOST: ${{ secrets.AZURE_REDIS_HOST }}
        AZURE_REDIS_PWD: ${{ secrets.AZURE_REDIS_PWD }}